# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cardano Foundation
email: admin@iohk.io
description: > # this means to ignore newlines until "baseurl:"
  New age tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cardanofoundation.org" # the base hostname & protocol for your site
permalink: /:categories/:title
twitter_username: CardanoFoundation
github_username:  jekyll

# Build settings
markdown: kramdown

# The all languages used
languages:          ['en', 'ja']

# If not config, the first item of languages will be used as the default.
language_default:   'en'

